#!/bin/bash
#

set -e

echo "Generating live system..."
sudo su -c "cd live && lb clean && lb build && cp binary/live/vmlinuz* binary/live/initrd.img* binary/live/filesystem.squashfs /var/www/" root

