#!/bin/bash
#
# Create cloned user for dolly
#

set -e

CLONED_HOME=/home/cloned
KEYGEN=`which ssh-keygen`

# Add user cloned
sudo useradd --home $CLONED_HOME --create-home --system --shell /bin/bash cloned

# Generate SSH-keys
sudo su -c "${KEYGEN} -t rsa -f ${CLONED_HOME}/.ssh/id_rsa -C '' -N ''" cloned

# Add cloned public key to root live user
sudo cat ${CLONED_HOME}/.ssh/id_rsa.pub > live/config/chroot_local-includes/root/.ssh/authorized_keys

