/*
 * File: app/view/AddComputerWindow.js
 * Date: Sun Oct 09 2011 21:00:32 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('IAD.view.AddComputerWindow', {
    extend: 'IAD.view.ui.AddComputerWindow',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});