/*
 * File: app/view/AddImage.js
 * Date: Mon Nov 21 2011 16:40:39 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('IAD.view.AddImage', {
    extend: 'IAD.view.ui.AddImage',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});