/*
 * File: app/view/MainWindow.js
 * Date: Sun Oct 09 2011 19:59:18 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('IAD.view.MainWindow', {
    extend: 'IAD.view.ui.MainWindow',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
}});