/*
 * File: app/view/MyWindow.js
 * Date: Sat Oct 08 2011 20:23:03 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('IAD.view.MyWindow', {
    extend: 'IAD.view.ui.MyWindow',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});