/*
 * File: app/store/ClassesStore.js
 * Date: Tue Dec 13 2011 14:05:45 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IAD.store.ClassesStore', {
    extend: 'Ext.data.TreeStore',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ClassesStore',
            folderSort: true,
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'mac'
                },
                {
                    name: 'ip'
                },
                {
                    name: 'classId'
                },
                {
                    name: 'computerId'
                },
                {
                    dateFormat: 'U',
                    name: 'updateDate',
                    type: 'date'
                },
                {
                    name: 'imageName'
                }
            ]
        }, cfg)]);
    }
});