/*
 * File: app/store/CloningStore.js
 * Date: Sat Oct 01 2011 20:11:19 GMT+0400
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IAD.store.CloningStore', {
    extend: 'Ext.data.TreeStore',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CloningStore',
            folderSort: true,
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'classId'
                },
                {
                    name: 'computerId'
                },
                {
                    name: 'name'
                },
                {
                    name: 'mac'
                },
                {
                    name: 'ip'
                },
                {
                    name: 'status'
                },
                {
                    name: 'statusDesc'
                }
            ]
        }, cfg)]);
    }
});