#!/bin/bash
#
# dolly-project.org
#

set -e

# Print usage information
usage() {
  echo 'Usage:	dolly -m|--mode save -t|--list "192.168.0.1" "dirname"
        dolly -m|--mode restore -t|--list "192.168.0.1 192.168.0.2..." "dirname"'
}

E_SHELL=64
E_OPTERR=65
E_PATHERR=66
E_MODE=67
E_GETOPT=68
E_LIST=69
E_IFACE=70

# Check current shell
if [ "${SHELL}" != "/bin/bash"  ]
then
  echo "Error: only BASH shell supported"
  echo
  exit $E_SHELL
fi

# Check if any parameters provided
if [ "$#" -eq 0 ]
then
  usage
  exit $E_OPTERR
fi

# TODO
# Check how many arguments provided from daemon
#if [ "$#" -qt 5 ]
#then
#  usage
#  exit $E_OPTERR
#fi

# For details see: /usr/share/doc/util-linux/examples/getopt-parse.bash
ARGS=`getopt --name 'dolly' --options hm:t: --longoptions help,mode:,list: -- "$@"`
eval set -- "$ARGS"
while true
do
  case "$1" in
    -h|--help)		usage;			exit 0;;
    -m|--mode)		MODE=$2;		shift 2;;
    -t|--list)		LIST=$2;		shift 2;;
    --)			shift;			break;;
    *)			echo "Getopt error!";	exit $E_GETOPT;;
  esac
done

# Check which mode is used
shopt -s nocasematch
if [ "$MODE" == "save" ]
then
  MODE=save
elif [ "$MODE" == "restore" ]
then
  MODE=restore
else
  echo "Error: wrong mode is selected"
  exit $E_MODE
fi
shopt -u nocasematch


############################### RESTORING #####################################
if [ "$MODE" == "restore" ]
then

# Check if path provided and exist
IMAGEPATH="/home/cloned/$1"
if [ ! -d "$IMAGEPATH" ]
then
  echo "Error: image path does not exist"
  exit $E_PATHERR
fi

# TODO
# Check if current user can change directory to $IMAGEPATH
# Check if image files are readable
# Check for duplicates in lists of hosts

# Number of hosts to clone
NUM_LIST=`echo $LIST | wc -w`

# TODO fix subnet detection (use CIDR logic - sipcalc?)
SUBNET=`echo ${LIST} | awk 'BEGIN { FS = "." } ; { print $1 "." $2 "." $3 "." }'`
SUBNETS=`for IP in ${LIST}
do
  echo $IP | awk 'BEGIN { FS = "." } ; { print $1 "." $2 "." $3 "." }'
done | sort | uniq | wc -l
`
# Target IP addresses must be in the same subnet
if [ "${SUBNETS}" -ne "1" ]
then
  echo "Error: target IP addresses in different subnets"
  exit $E_LIST
fi

# Look for needed interface for target subnet
IFACE=`ip -4 -oneline addr show | grep -F "${SUBNET}" | awk '{ print $2 }'`
if [ -z "$IFACE" ]
then
  echo "Error: interface not found for target subnet"
  exit $E_IFACE
fi

echo "Cloning started at: `date`"

# Cloning partition table
for CLONE in ${LIST}
do
  # Create parition table
  cat ${IMAGEPATH}/sda-pt.sf | ssh root@${CLONE} sfdisk -uS --Linux --quiet /dev/sda
  # Copy Dolly script to target (also works as pause before PT reread)
  scp "/usr/local/bin/dolly-receiver" root@${CLONE}:/sbin/
  # TODO Use ssh root@${CLONE} /sbin/blockdev --rereadpt $DEV
  #  to reread partition table
done

# Cloning partitions
cd ${IMAGEPATH}
for PART in `ls sda*.img.gz | awk 'BEGIN { FS = "." } ; { print $1 }'`
do
  for CLONE in ${LIST}
  do
    # Execute Dolly script
    ssh root@${CLONE} /usr/bin/screen -d -m /sbin/dolly-receiver /dev/${PART}
    sleep 1
    # TODO resize NTFS?
    #add "ntfsresize --force --no-progress-bar $1" to cloned-restore?
  done
  # Wait for udpcast to settle
  sleep 5
  # Run sender with speed limit and frequent statistics output
  /usr/bin/udp-sender --file "${IMAGEPATH}/${PART}.img.gz" --interface ${IFACE} --full-duplex --min-receivers ${NUM_LIST} --nokbd --max-bitrate 80m --stat-period 1
  # Wait for data is received by slow targets
  # This fixes "gzip: stdin error unexpected end of file"
  # Sometimes client disconnects after finishing 1st partition. Slow clients?
  sleep 30
done

# Cloning MBR and hidden data
for CLONE in ${LIST}
do
  # Copy MBR boot record
  cat ${IMAGEPATH}/sda-mbr.bin | ssh root@${CLONE} "dd of=/dev/sda"
  # Copy over hidden data between 1 and 63 sectors that containing GRUB stage 1.5
  # TODO automatically get hidden sectors location from partition table
  cat ${IMAGEPATH}/sda-hiddensectors.bin | ssh root@${CLONE} dd bs=512 count=62 seek=1 of=/dev/sda
  # Reboot target computer
  ssh root@${CLONE} reboot
done

echo "Cloning finished at: `date`"
fi


################################## SAVING #####################################
if [ "$MODE" == "save" ]
then

# Creating directory for new image
IMAGEPATH="/home/cloned/$1"
mkdir "${IMAGEPATH}" || exit $E_PATHERR
cd "${IMAGEPATH}"

# Check if single address provided
HOSTCOUNT=`echo $LIST | wc -w`
if [ "${HOSTCOUNT}" -ne "1" ]
then
  echo "Error: multiple targets not allowed in save mode"
  exit $E_LIST
fi

CLONE=$LIST

# TODO fix subnet detection (use CIDR logic - sipcalc?)
SUBNET=`echo ${LIST} | awk 'BEGIN { FS = "." } ; { print $1 "." $2 "." $3 "." }'`

# Look for needed interface for target subnet
IFACE=`ip -4 -oneline addr show | grep -F "${SUBNET}" | awk '{ print $2 }'`
if [ -z "$IFACE" ]
then
  echo "Error: interface not found for target subnet"
  exit $E_IFACE
fi

echo "Imaging started at: `date`"

# Dumping partition table
ssh root@${CLONE} "sfdisk -d /dev/sda" > sda-pt.sf

# Dumping MBR boot code
ssh root@${CLONE} "dd if=/dev/sda bs=448 count=1" > sda-mbr.bin

# Dumping hidden sectors
# TODO automatically get hidden sectors location from partition table
ssh root@${CLONE} "dd if=/dev/sda bs=512 count=62 skip=1" > sda-hiddensectors.bin

# Copy Dolly script to target
scp -q "/usr/local/bin/dolly-sender" root@${CLONE}:/sbin/

# TODO: if image have more than one net interface?
for PART in `ssh root@${CLONE} "ls /dev/sda?*" | awk 'BEGIN { FS = "/" } ; { print $3 }'`
do
  echo "Saving partition ${PART}"
  # Run sender and put process in background
  ssh root@${CLONE} /usr/bin/screen -d -m /sbin/dolly-sender /dev/${PART}
  # Wait for udpcast to settle
  sleep 5
  # Use udpcast to receive data
  /usr/bin/udp-receiver --interface ${IFACE} --nokbd --stat-period 1 > "${IMAGEPATH}/${PART}.img.gz"
done

ssh root@${CLONE} poweroff

echo "Imaging finished at: `date`"
fi

exit 0
