/*
 * File: app/view/ui/AddImage.js
 * Date: Mon Nov 21 2011 16:42:31 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IAD.view.ui.AddImage', {
    extend: 'Ext.window.Window',

    height: 126,
    id: 'AddImage',
    width: 438,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    bodyPadding: 10,
    title: 'Создание образа',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'name',
                    fieldLabel: 'Имя образа',
                    flex: 1
                },
                {
                    xtype: 'textfield',
                    itemId: 'path',
                    fieldLabel: 'Путь',
                    flex: 1
                },
                {
                    xtype: 'container',
                    layout: {
                        align: 'middle',
                        pack: 'end',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'addComputer',
                            text: 'Добавить',
                            margins: '0 5 0 0'
                        },
                        {
                            xtype: 'button',
                            itemId: 'cancel',
                            text: 'Отмена'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});