/*
 * File: app/view/ui/MyWindow.js
 * Date: Sun Oct 09 2011 19:29:12 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IAD.view.ui.MyWindow', {
    extend: 'Ext.window.Window',

    height: 503,
    id: 'IADWindow',
    width: 750,
    layout: {
        type: 'fit'
    },
    title: 'Модуль управления системы автоматизированного клонирования жестких дисков',

    initComponent: function() {
        var me = this;
        me.items = [
            {
                xtype: 'tabpanel',
                itemId: 'navTabs',
                activeTab: 0,
                items: [
                    {
                        xtype: 'panel',
                        itemId: 'classesTab',
                        layout: {
                            type: 'border'
                        },
                        title: 'Состав сети',
                        items: [
                            {
                                xtype: 'treepanel',
                                height: 250,
                                itemId: 'editClassesGrid',
                                width: 400,
                                title: '',
                                store: 'MyJsonTreeStore',
                                rootVisible: false,
                                region: 'center',
                                items: [
                                    {
                                        xtype: 'menu',
                                        floating: false,
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                ],
                                viewConfig: {

                                },
                                columns: [
                                    {
                                        xtype: 'treecolumn',
                                        width: 100,
                                        dataIndex: 'className',
                                        text: 'Компьютер'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        width: 100,
                                        dataIndex: 'macAddress',
                                        text: 'MAC'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        text: 'Дата обновления'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        flex: 1,
                                        text: 'Образ'
                                    }
                                ],
                                dockedItems: [
                                    {
                                        xtype: 'toolbar',
                                        itemId: 'toolbar',
                                        dock: 'top',
                                        items: [
                                            {
                                                xtype: 'button',
                                                itemId: 'addClass',
                                                text: 'Добавить класс'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            align: 'stretch',
                            type: 'vbox'
                        },
                        title: 'Управление образами'
                    },
                    {
                        xtype: 'panel',
                        title: 'Клонирование'
                    }
                ]
            }
        ];
        me.callParent(arguments);
    }
});